# Generated by Django 2.2.2 on 2023-04-17 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('pickup_location', models.CharField(blank=True, max_length=100, null=True)),
                ('destination', models.CharField(blank=True, max_length=100, null=True)),
                ('distance', models.CharField(blank=True, max_length=100, null=True)),
                ('pickup_date', models.DateField(blank=True, null=True)),
                ('pickup_time', models.TimeField(blank=True, null=True)),
                ('num_passengers', models.PositiveIntegerField(blank=True, null=True)),
                ('vehicle_type', models.CharField(blank=True, max_length=50, null=True)),
                ('total_amount', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('is_anonymous', models.BooleanField(blank=True, default=False, null=True)),
                ('is_authenticated', models.BooleanField(blank=True, default=True, null=True)),
            ],
        ),
    ]
